# Generated by Django 4.0.4 on 2024-03-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tests'},
        ),
    ]
